# Changes here will be overwritten by Copier
_commit: fb7354f
_src_path: https://github.com/lenskit/lk-project-template.git
package_name: seedbank
project_descr: Common infrastructure for seeding random number generators.
project_name: seedbank
project_title: SeedBank
require_lint: true
start_year: 2021
typecheck: true
