# Changes here will be overwritten by Copier
_commit: 0233d57
_src_path: https://github.com/lenskit/lk-project-template.git
owner: Drexel University and contributors
package_name: seedbank
project_descr: Common infrastructure for seeding random number generators.
project_name: seedbank
project_title: SeedBank
require_lint: true
start_year: 2021
typecheck: true
